[package]
name = "tap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"
raw-window-handle = "0.5"
winit = "0.28.0"

ash = "0.37.3+1.3.251"
ash-window = "0.12.0"